#!/bin/sh

xrandr \
        --output eDP1 --primary --mode 1920x1080 --pos 0x260 --rotate normal \
        --output DP1 --off \
        --output DP2 --mode 2560x1600 --pos 1920x0 --rotate normal \
        --output DP3 --off \
        --output VIRTUAL1 --off
