#!/bin/sh

xrandr \
        --output eDP-1 --primary --mode 1920x1080 --pos 960x2160 --rotate normal \
        --output eDP-2 --primary --mode 1920x1080 --pos 960x2160 --rotate normal \
        --output eDP-1-1 --off \
        --output HDMI-1-1 --off \
        --output DP-1-1 --off \
        --output DP-1-2 --mode 3840x2160 --pos 0x0 --rotate normal

i3-msg 'workspace 1; move workspace to output DP-1-2'
